version: '3.8'

services:
  dmit_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: dmit_proxy_manager
    ports:
      - '81:81'
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  dmit_proxy_manager_db:
    image: 'jc21/mariadb-aria:10.4.15'
    container_name: dmit_proxy_manager_db
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  dmit_network:
    external: true
